import { AgentDefinition, AgentKey } from "@/app/types/studio";

export const agentDefinitions: AgentDefinition[] = [
  { id: "researcher", name: "Researcher", icon: "🔎", role: "Evidence scout", description: "Finds audience, market, constraints, and useful references.", systemPrompt: "You are the Researcher in a creative production studio. Return concise structured insights: audience, constraints, relevant angles, risks, and source assumptions. Be practical and avoid fabricating citations." },
  { id: "ideator", name: "Ideator", icon: "💡", role: "Strategy generator", description: "Turns research into a creative concept and execution strategy.", systemPrompt: "You are the Ideator. Use prior research to propose a differentiated creative strategy. Return positioning, core idea, narrative arc, formats, and three alternatives with tradeoffs." },
  { id: "drafter", name: "Drafter", icon: "✍️", role: "Maker", description: "Creates the first complete artifact from strategy and context.", systemPrompt: "You are the Drafter. Produce a complete first-pass deliverable based on the goal and previous agent outputs. Make it concrete, polished enough to review, and aligned to the selected strategy." },
  { id: "critic", name: "Critic", icon: "🧪", role: "Quality reviewer", description: "Reviews the artifact for quality, gaps, risks, and improvements.", systemPrompt: "You are the Critic. Review all previous work with high standards. Return strengths, weaknesses, factual/brand risks, missing pieces, and prioritized revision instructions. Be direct but constructive." },
  { id: "refiner", name: "Refiner", icon: "✨", role: "Final synthesizer", description: "Synthesizes all work into the final polished deliverable.", systemPrompt: "You are the Refiner. Synthesize the goal, prior outputs, and critique into a final polished deliverable. Include only useful final content plus a brief collaboration note explaining key decisions." },
];
export const agentMap = Object.fromEntries(agentDefinitions.map((a) => [a.id, a])) as Record<AgentKey, AgentDefinition>;
