"use client";
import { motion } from "framer-motion";
import { StudioAgentState } from "@/app/types/studio";
import { cn } from "@/app/lib/utils";

export function Pipeline({ agents, activeAgent, onReorder, onSelect }: { agents: StudioAgentState[]; activeAgent?: string; onReorder: (a: StudioAgentState[]) => void; onSelect: (a: StudioAgentState) => void }) {
  const move = (from: number, delta: number) => { const to = from + delta; if (to < 0 || to >= agents.length) return; const next = [...agents]; const [item] = next.splice(from, 1); next.splice(to, 0, item); onReorder(next); };
  return <div className="flex gap-4 overflow-x-auto pb-4">{agents.map((agent, index) => <motion.article layout key={agent.id} draggable onDragStart={(e) => e.dataTransfer.setData("text/plain", String(index))} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const from = Number(e.dataTransfer.getData("text/plain")); const next = [...agents]; const [item] = next.splice(from, 1); next.splice(index, 0, item); onReorder(next); }} onClick={() => onSelect(agent)} className={cn("min-w-64 cursor-pointer rounded-3xl border p-5 text-left", activeAgent === agent.id ? "border-cyan-300 bg-cyan-300/10" : "border-slate-700 bg-slate-900/80")}><div className="flex items-center justify-between"><span className="text-3xl">{agent.icon}</span><span className="rounded-full bg-slate-800 px-3 py-1 text-xs capitalize text-cyan-200">{agent.status}</span></div><h3 className="mt-4 text-xl font-semibold">{agent.name}</h3><p className="text-sm text-cyan-200">{agent.role}</p><p className="mt-2 text-sm text-slate-400">{agent.description}</p><div className="mt-4 flex gap-2"><button onClick={(e)=>{e.stopPropagation(); move(index,-1);}} className="rounded-full border border-slate-700 px-3 py-1 text-xs">←</button><button onClick={(e)=>{e.stopPropagation(); move(index,1);}} className="rounded-full border border-slate-700 px-3 py-1 text-xs">→</button></div></motion.article>)}</div>;
}
