"use client";
import { useEffect, useState } from "react";
import { Settings, Sparkles, Copy, Download } from "lucide-react";
import { Pipeline } from "@/app/components/studio/pipeline";
import { AgentModal } from "@/app/components/studio/agent-modal";
import { useStudioStore } from "@/app/lib/studio-store";
import { downloadMarkdown } from "@/app/lib/utils";
import { StudioAgentState } from "@/app/types/studio";

export default function StudioPage() {
  const store = useStudioStore(); const [selected, setSelected] = useState<StudioAgentState>(); const [error, setError] = useState("");
  useEffect(() => { if (!store.finalDeliverable && !store.isRunning) store.runPipeline().catch((e) => setError(e.message)); }, []);
  async function run() { setError(""); try { await store.runPipeline(); } catch (e) { setError(e instanceof Error ? e.message : "Failed"); } }
  return <main className="min-h-screen bg-slate-950 text-slate-100"><nav className="flex items-center justify-between border-b border-slate-800 px-6 py-4"><div className="flex items-center gap-3 text-lg font-semibold"><Sparkles className="text-cyan-300"/> The Studio</div><Settings className="text-slate-400"/></nav><div className="mx-auto max-w-7xl p-6"><section className="mb-6 rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><label className="text-sm text-cyan-200">Creative command</label><div className="mt-3 flex gap-3"><input value={store.goal} onChange={(e) => store.setGoal(e.target.value)} className="flex-1 rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-cyan-300"/><button onClick={run} disabled={store.isRunning} className="rounded-2xl bg-cyan-300 px-5 font-semibold text-slate-950 disabled:opacity-60">{store.isRunning ? "Producing…" : "Run pipeline"}</button></div>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}</section><Pipeline agents={store.agents} activeAgent={store.activeAgent} onReorder={store.reorder} onSelect={setSelected}/><div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="glass rounded-3xl p-5"><h2 className="text-xl font-semibold">Activity Timeline</h2><div className="mt-4 space-y-3">{store.timeline.length === 0 ? <p className="text-slate-400">Agents will report collaboration steps here.</p> : store.timeline.map((e) => <div key={e.id} className="rounded-2xl bg-slate-950/80 p-3"><p className="font-medium">{e.title}</p><p className="text-sm text-slate-400">{e.description}</p></div>)}</div></section><section className="glass rounded-3xl p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Final Deliverable</h2><div className="flex gap-2"><button className="rounded-full border border-slate-700 p-2" onClick={() => navigator.clipboard.writeText(store.finalDeliverable)}><Copy size={16}/></button><button className="rounded-full border border-slate-700 p-2" onClick={() => downloadMarkdown("the-studio-deliverable.md", store.finalDeliverable)}><Download size={16}/></button></div></div><pre className="mt-4 min-h-96 whitespace-pre-wrap rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-slate-200">{store.finalDeliverable || "Your refined output will appear here."}</pre></section></div></div><AgentModal agent={selected} onClose={() => setSelected(undefined)} onFeedback={(message) => selected && store.rerunAgent(selected.id, message).catch((e) => setError(e.message))}/></main>;
}
